### ISSUE TITLE
Make the meta data for enrollment configurable

### ISSUE THREAD

**Issue by linked0** [bosagora/agora#520]
There are some meta data to be configurable for enrollment and pre-image. So we will select the meta data for being configurable and make the `EnrollmentManage` restore the data.

Enrolled validators should always make sure that their preimage are available to other nodes in a timely manner. The issue is what is the best period for revealing the preimage. So It should be cofigurable as an item like  in the configuration file.

 Definition of Done:

- [x] Include the period of revealing pre-image, or `reveal_preimage_period` is in the config file 
- [x] Include the an aging period after which an enrollment is deleted from the pool
- [x] Include the period of revelation of pre-image
- [x] Pass the meta value to the enrollment manager.

This is related to #492

**Comment by Geod24** [comment]
This has been addressed.

1) https://github.com/bosagora/agora/blob/2558cd782c4cbcf82aed2d9fe684f85e85511842/source/agora/common/Config.d#L251-L252

2) Enrollments are only valid for one height since #1902 ;

3, 4) See 1
