### ISSUE TITLE
[upstream] Tracker for upstream bugs

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#561]
This issue is a list of bugs that affects us. Some of them are just comments at this point, and I will add a link to bugzilla once properly filled.

Confirmed:
- Documentation (https://dlang.org/spec/cpp_interface.html) is obsolete: Does not contain the `extern(C++, "ns")` syntax ([issue](https://issues.dlang.org/show_bug.cgi?id=19360)), mentions that ctor / copy ctor / operator overloads can't be called (it's wrong), etc... We have a [related issue](https://github.com/bpfkorea/agora/issues/560), and addressing it might have a large overlap with overhauling the official documentation.
- [Druntime's exception definition is broken](https://issues.dlang.org/show_bug.cgi?id=19271). Related https://github.com/bpfkorea/agora/issues/298
- ~[Callee erroneously calls the destructor in D](https://issues.dlang.org/show_bug.cgi?id=20235)~ Fixed v2.096.0
- [Wrong mangling for copy ctor on non-Windows](https://issues.dlang.org/show_bug.cgi?id=20208)
- ~[Last but not least: 5570 aka "ABI not followed when passing struct or complex number as function parameter"](https://issues.dlang.org/show_bug.cgi?id=5570).~ Fixed v2.096.0
- ~[ABI tags support (for `std::string`)](https://issues.dlang.org/show_bug.cgi?id=19949)~
- ~[DIP1000 does not catch implicit conversion of scope delegate to non-scope delegate](https://issues.dlang.org/show_bug.cgi?id=20868)~
- [Self-referential structure do not infer `@safe`](https://issues.dlang.org/show_bug.cgi?id=20724)
- ~[Forward references leads to `extern(C++, class|struct)` being ignored](https://issues.dlang.org/show_bug.cgi?id=20700)~ Fixed
- [extern(C++, class|struct) should not apply to inner types](https://issues.dlang.org/show_bug.cgi?id=20701)
- ~[Copy constructor disable default struct constructor](https://issues.dlang.org/show_bug.cgi?id=20695)~ Fixed v2.096.0
- [`__traits(isReturnOnStack)` is completely broken](https://issues.dlang.org/show_bug.cgi?id=20752)
- ~[BLOCKER] [Cannot create const arrays mixing immutable and mutable structs with indirections](https://issues.dlang.org/show_bug.cgi?id=20938)~: Resolved fixed in 2.093.0
- [`ref` + `delegate` might lead to memory corruption, especially with Fibers](https://issues.dlang.org/show_bug.cgi?id=20956)
- [MAJOR] `Exception.toString()` doesn't print a stack trace on LDC+Alpine ([related](https://github.com/ldc-developers/ldc/issues/115))
- [MAJOR] [`Exception.toString()` needs a compiler hack on OSX](https://issues.dlang.org/show_bug.cgi?id=20510)
- [`Exception.toString()` relies on `backtrace_symbols` which causes issues with frame pointer](https://issues.dlang.org/show_bug.cgi?id=11870)
- [`Exception.toString()` is mind-boggingly slow](https://gist.github.com/Geod24/c55e7765978d978e62c1a46631841b12)
- ~[[MAJOR] Array comparison mismatch for aggregates and > 3 levels of indirection](https://issues.dlang.org/show_bug.cgi?id=21012)~ To be fixed in 2.094.0
- [Cannot switch before immutable initialization in constructor](https://issues.dlang.org/show_bug.cgi?id=21080)
- [Adding elements while iterating on an AA can SIGSEGV](https://issues.dlang.org/show_bug.cgi?id=12218#c7)
- ~[[MAJOR] Wrong mangling for parameter packs (affect `std::make_shared`)](https://issues.dlang.org/show_bug.cgi?id=21283)~ Will be fixed in v2.095.0
- ~[Calling AA.remove from a destructor might lead to InvalidMemoryOperationError](https://issues.dlang.org/show_bug.cgi?id=21442) Temporarily fixed~ Fixed v2.095.0
- [`@safe` issues with `iota` + `array`](https://issues.dlang.org/show_bug.cgi?id=21583)
- [DUB: `sourcePath` does not behave as documented](https://github.com/dlang/dub/issues/1913) (previously #1326).

Issues that blocks improvements:
- ~[Linker errors with `-checkaction=context` (needs rvalue refs)](https://github.com/bpfkorea/agora/pull/142)~
- ~[`-preview=rvaluerefparam` doesn't work with `T.init`](https://issues.dlang.org/show_bug.cgi?id=20704)~ Use `-preview=in` instead
- ~[`-preview=rvaluerefparam` doesn't work with template deduction](https://issues.dlang.org/show_bug.cgi?id=20705)~ Use `-preview=in` instead
- ~[`-preview=rvaluerefparam` doesn't work with copy ctors and does a dumb copy](https://issues.dlang.org/show_bug.cgi?id=20706)~ Use `-preview=in` instead

Unconfirmed:
- [Windows linker issue with templates](https://issues.dlang.org/show_bug.cgi?id=20805)
- [C++11 mangling issues](https://issues.dlang.org/show_bug.cgi?id=14956)
- ~[ABI issue to investigate](https://issues.dlang.org/show_bug.cgi?id=19841)~ Wrong
- ~[Small struct by value wrong ABI issue](https://issues.dlang.org/show_bug.cgi?id=19179)~
- ~[Mangling issue with size_t](https://issues.dlang.org/show_bug.cgi?id=16289), likely not relevant anymore.~ Confirmed fixed
- [Probably incomplete documentation thanks to this](https://issues.dlang.org/show_bug.cgi?id=14898)
- ~[Random OSX ABI issue to investigate...](https://issues.dlang.org/show_bug.cgi?id=18894)~ Invalid issue.
- [C++ delegates were a problem for us recently](https://issues.dlang.org/show_bug.cgi?id=7925)
- ~[Yet another ABI issue](https://issues.dlang.org/show_bug.cgi?id=14203)~ Fixed in v2.094.0
- [Template return type mangling issue](https://issues.dlang.org/show_bug.cgi?id=20679)
- [Template const parameter mangling issue](https://issues.dlang.org/show_bug.cgi?id=20685)
- [scope (failure) breaks safety](https://issues.dlang.org/show_bug.cgi?id=21443)

Not blocking but future-relevant:
- [Issue about head const, relevant for STL port, but probably invalid](https://issues.dlang.org/show_bug.cgi?id=19260)
- [Classes are always mangled as pointer, but sometimes all you need to get the job is a reference](https://issues.dlang.org/show_bug.cgi?id=18896)
- [Debug infos for extern(C++)](https://issues.dlang.org/show_bug.cgi?id=15023) can probably be worked around much better via LDC/GDC ? => There's a PR in druntime for it.
- [Profiling code segfaults with threads on LDC](https://github.com/ldc-developers/ldc/issues/3447)
- [Field.init is typeof(Field).init, not the actual `init`](https://issues.dlang.org/show_bug.cgi?id=21016).
- [Cannot have `scope immutable` class (e.g. ConsensusParams)](https://issues.dlang.org/show_bug.cgi?id=19272)

Other:
- [Wrong destructor mangling for classes](https://issues.dlang.org/show_bug.cgi?id=19505)
- ~[Pragma(mangle) ignored for dtors](https://issues.dlang.org/show_bug.cgi?id=19504)~ Already fixed, added a [test to DMD](https://github.com/dlang/dmd/pull/10811)
- [ICE on D-specific type (diag)](https://issues.dlang.org/show_bug.cgi?id=16575) (also https://issues.dlang.org/show_bug.cgi?id=19347 somewhat relevant)
- Don't use static array: [1](https://issues.dlang.org/show_bug.cgi?id=19953), [2](https://issues.dlang.org/show_bug.cgi?id=17359), [3](https://issues.dlang.org/show_bug.cgi?id=15505), [42](https://issues.dlang.org/show_bug.cgi?id=8887)
- [Add ability to interact with thread-local variables](https://issues.dlang.org/show_bug.cgi?id=15523)
- [`static foreach` + extern(C++) => ICE](https://issues.dlang.org/show_bug.cgi?id=19482)
- [Casting classes from interface doesn't work](https://issues.dlang.org/show_bug.cgi?id=19267)
- [Corner case mangling issue when mixing `extern(D)` type and `extern(C++)` functions](https://issues.dlang.org/show_bug.cgi?id=19101)
- [shared is broken with `extern(C++)` (but not only)](https://issues.dlang.org/show_bug.cgi?id=7024)

**Comment by Geod24** [comment]
Another one, not an ABI issue though: https://forum.dlang.org/thread/mailman.2386.1584953641.31109.digitalmars-d-bugs@puremagic.com

**Comment by Geod24** [comment]
Two issues we found on Windows:
- [ ] [Forward references leads to `extern(C++, class|struct)` being ignored](https://issues.dlang.org/show_bug.cgi?id=20700)
- [ ] [extern(C++, class|struct) should not apply to inner types](https://issues.dlang.org/show_bug.cgi?id=20701)

They are not blockers, since we identified them and can work around them.

**Comment by Geod24** [comment]
I tried enabling `-preview=rvaluerefparam`:
- [ ] [It doesn't work with `T.init`](https://issues.dlang.org/show_bug.cgi?id=20704)
- [ ] [It doesn't work with template deduction](https://issues.dlang.org/show_bug.cgi?id=20705)
- [ ] [It doesn't work with copy ctors and does a dumb copy](https://issues.dlang.org/show_bug.cgi?id=20706)

**Comment by Geod24** [comment]
- [ ] [I tried using `__traits(isReturnOnStack)` and failed](https://issues.dlang.org/show_bug.cgi?id=20752)

**Comment by Geod24** [comment]
https://github.com/bpfkorea/agora/issues/561#issuecomment-604798817

The forward reference issue got fixed with DMD v2.091.1 though (LDC 1.21.0).

**Comment by Geod24** [comment]
Well, changing this to be "upstream bugs". I was looking into trace informations implementation, as currently it's hard to develop on OSX, not to mention I was hitting timeout when debugging LocalRest.

Turns out the traceinfo implementation is terribly inefficient.

- [ ] `Exception.toString()` doesn't print a stack trace on LDC+Alpine ([related](https://github.com/ldc-developers/ldc/issues/115))
- [ ] [It doesn't work on OSX without compiler hack](https://issues.dlang.org/show_bug.cgi?id=20510)
- [ ] [It relies on `backtrace_symbols` which causes issues with frame pointer](https://issues.dlang.org/show_bug.cgi?id=11870)
- [ ] [It's mind-boggingly slow](https://gist.github.com/Geod24/c55e7765978d978e62c1a46631841b12)

I started to implement 20510 on my free time.

**Comment by Geod24** [comment]
Dammit son:
- [ ] [Cannot create const arrays mixing immutable and mutable structs with indirections](https://issues.dlang.org/show_bug.cgi?id=20938)

**Comment by Geod24** [comment]
Today's fun one:
- [ ] [DIP1000 is still pretty darn useless in catching escape bugs](https://issues.dlang.org/show_bug.cgi?id=20956)

**Comment by Geod24** [comment]
I consolidated everything in the first post and removed the 6 or so comments. There have been quite a few improvements we made, and there's quite a few left to do.
